### ISSUE TITLE
Unable to install Feather

### ISSUE THREAD

**Issue by zpencerguy** [Microsoft/AzureNotebooks#227]
Unable to install Feather using pip.

HTTP Error 403: Forbidden
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-q03c3ve9/feather/

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [X] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by crwilcox** [comment]
I just tried installing feather locally and it is broken. For downloading they are using an http link that has to be https. If you fix that you will have other install issues with Python 3.6
`pip install feather` hasn't been updated in 6 years so it likely is not python 3 compatible.

Do you mean to install feather? Or are you trying to install Feather to work with Apache Arrow -> `pip install feather-format`?

If you mean to `pip install feather` you can do so on Python 2.7, but only after hand editing the `distribute_setup.py` file to use https.
```
(py36) C:\Users\crwilcox\venvs\py36> pip install feather
Collecting feather
  Downloading feather-0.9.1dev.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.14.tar.gz
    Traceback (most recent call last):
      File "C:\Users\crwilcox\AppData\Local\Temp\pip-build-nlozpszg\feather\distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\crwilcox\AppData\Local\Temp\pip-build-nlozpszg\feather\setup.py", line 3, in <module>
        distribute_setup.use_setuptools()
      File "C:\Users\crwilcox\AppData\Local\Temp\pip-build-nlozpszg\feather\distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "C:\Users\crwilcox\AppData\Local\Temp\pip-build-nlozpszg\feather\distribute_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "C:\Users\crwilcox\AppData\Local\Temp\pip-build-nlozpszg\feather\distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "C:\Program Files\Python36\lib\urllib\request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "C:\Program Files\Python36\lib\urllib\request.py", line 532, in open
        response = meth(req, response)
      File "C:\Program Files\Python36\lib\urllib\request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "C:\Program Files\Python36\lib\urllib\request.py", line 570, in error
        return self._call_chain(*args)
      File "C:\Program Files\Python36\lib\urllib\request.py", line 504, in _call_chain
        result = func(*args)
      File "C:\Program Files\Python36\lib\urllib\request.py", line 650, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 403: SSL is required

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\crwilcox\AppData\Local\Temp\pip-build-nlozpszg\feather\
```

**Comment by zpencerguy** [comment]
Thanks @crwilcox you called it, my intent was actually for Appache Arrow's feather-format. I now have this working after pip install feather-format. Was going off an old post...
