### ISSUE TITLE
ModuleNotFoundError: No module named 'keras' 

### ISSUE THREAD

**Issue by mforinadxc** [Microsoft/AzureNotebooks#526]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
Notebook experiments fails because compute does not find 'keras' 

No Title
The experiment failed. Finalizing run...
Logging experiment finalizing status in history service
Traceback (most recent call last):
  File "azureml-setup/context_manager_injector.py", line 70, in execute_with_context
    runpy.run_path(sys.argv[0], globals(), run_name="__main__")
  File "/azureml-envs/azureml_088906b35cdd6596b350e033526a1806/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/azureml-envs/azureml_088906b35cdd6596b350e033526a1806/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/azureml-envs/azureml_088906b35cdd6596b350e033526a1806/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "train.py", line 7, in <module>
    from keras.models import Sequential # Initialise our neural network model as a sequential network
ModuleNotFoundError: No module named 'keras' 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

%%writefile $script_folder/train.py

import argparse
import os
import numpy as np

import os
from keras.models import Sequential # Initialise our neural network model as a sequential network
from keras.layers import Conv2D # Convolution operation
from keras.layers import MaxPooling2D # Maxpooling function
from keras.layers import Flatten # Converting 2D arrays into a 1D linear vector.
from keras.layers import Dense # Perform the full connection of the neural network
from keras.preprocessing.image import ImageDataGenerator
from IPython.display import display
from PIL import Image
import cv2
import numpy as np
from sklearn.metrics import accuracy_score
from skimage import io, transform

#### Which language/kernel were you using when you experienced this issue?
    [] Python 3.6 

#### What time (please include time zone) did this occur?
always

#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by mforinadxc** [comment]
The experiment failed. Finalizing run...
Logging experiment finalizing status in history service
Traceback (most recent call last):
  File "azureml-setup/context_manager_injector.py", line 70, in execute_with_context
    runpy.run_path(sys.argv[0], globals(), run_name="__main__")
  File "/azureml-envs/azureml_088906b35cdd6596b350e033526a1806/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/azureml-envs/azureml_088906b35cdd6596b350e033526a1806/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/azureml-envs/azureml_088906b35cdd6596b350e033526a1806/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "train.py", line 7, in <module>
    from keras.models import Sequential # Initialise our neural network model as a sequential network
ModuleNotFoundError: No module named 'keras'

Traceback (most recent call last):
  File "azureml-setup/context_manager_injector.py", line 126, in <module>
    execute_with_context(cm_objects, options.invocation)
  File "azureml-setup/context_manager_injector.py", line 70, in execute_with_context
    runpy.run_path(sys.argv[0], globals(), run_name="__main__")
  File "/azureml-envs/azureml_088906b35cdd6596b350e033526a1806/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/azureml-envs/azureml_088906b35cdd6596b350e033526a1806/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/azureml-envs/azureml_088906b35cdd6596b350e033526a1806/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "train.py", line 7, in <module>
    from keras.models import Sequential # Initialise our neural network model as a sequential network
ModuleNotFoundError: No module named 'keras'
