### ISSUE TITLE
Install nbextensions?

### ISSUE THREAD

**Issue by rjleveque** [microsoft/AzureNotebooks#71]
Is it possible to install nbextensions?

For this library of notebooks: https://notebooks.azure.com/library/riemann_book

We have attempted to do this in the `Install-nbextensions.ipynb` notebook and run into several errors:

```
!jupyter nbextension enable --py widgetsnbextension

Exception while loading config file /home/nbuser/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/home/nbcommon/anaconda2_410/lib/python2.7/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/home/nbcommon/anaconda2_410/lib/python2.7/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/home/nbcommon/anaconda2_410/lib/python2.7/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/home/nbcommon/anaconda2_410/lib/python2.7/site-packages/ipython_genutils/py3compat.py", line 288, in execfile
        builtin_mod.execfile(filename, *where)
      File "/home/nbuser/.jupyter/jupyter_notebook_config.py", line 596, in <module>
        import bleach_whitelist
    ImportError: No module named bleach_whitelist
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK


```

and 

```
!jupyter contrib nbextension install --user

[I 00:48:34 InstallContribNbextensionsApp] jupyter contrib nbextension install --user
[I 00:48:34 InstallContribNbextensionsApp] Installing jupyter_contrib_nbextensions nbextension files to jupyter data directory
[I 00:48:34 InstallContribNbextensionsApp] Installing /home/nbcommon/anaconda2_410/lib/python2.7/site-packages/jupyter_contrib_nbextensions/nbextensions/tree-filter -> tree-filter
[I 00:48:34 InstallContribNbextensionsApp] Making directory: /home/nbuser/.local/share/jupyter/nbextensions/tree-filter/
Traceback (most recent call last):
  File "/home/nbuser/anaconda2_410/bin/jupyter-contrib", line 11, in <module>
    sys.exit(main())
  File "/home/nbcommon/anaconda2_410/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/nbcommon/anaconda2_410/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/nbcommon/anaconda2_410/lib/python2.7/site-packages/jupyter_contrib_core/application.py", line 50, in start
    super(JupyterContribApp, self).start()
  File "/home/nbcommon/anaconda2_410/lib/python2.7/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/home/nbcommon/anaconda2_410/lib/python2.7/site-packages/jupyter_contrib_nbextensions/application.py", line 209, in start
    super(ContribNbextensionsApp, self).start()
  File "/home/nbcommon/anaconda2_410/lib/python2.7/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/home/nbcommon/anaconda2_410/lib/python2.7/site-packages/jupyter_contrib_nbextensions/application.py", line 162, in start
    toggle_install_files(self._toggle_value, **kwargs_files)
  File "/home/nbcommon/anaconda2_410/lib/python2.7/site-packages/jupyter_contrib_nbextensions/install.py", line 95, in toggle_install_files
    mod.__name__, overwrite=overwrite, symlink=symlink, **kwargs)
  File "/home/nbcommon/anaconda2_410/lib/python2.7/site-packages/notebook/nbextensions.py", line 239, in install_nbextension_python
    destination=dest, logger=logger
  File "/home/nbcommon/anaconda2_410/lib/python2.7/site-packages/notebook/nbextensions.py", line 206, in install_nbextension
    os.makedirs(dest_dir)
  File "/home/nbcommon/anaconda2_410/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/nbuser/.local/share/jupyter/nbextensions/tree-filter/'
```

and

```
!jupyter nbextension enable equation-numbering/main

Exception while loading config file /home/nbuser/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/home/nbcommon/anaconda2_410/lib/python2.7/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/home/nbcommon/anaconda2_410/lib/python2.7/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/home/nbcommon/anaconda2_410/lib/python2.7/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/home/nbcommon/anaconda2_410/lib/python2.7/site-packages/ipython_genutils/py3compat.py", line 288, in execfile
        builtin_mod.execfile(filename, *where)
      File "/home/nbuser/.jupyter/jupyter_notebook_config.py", line 596, in <module>
        import bleach_whitelist
    ImportError: No module named bleach_whitelist
Enabling notebook extension equation-numbering/main...
      - Validating: problems found:
        - require?  X equation-numbering/main
```

**Comment by rjleveque** [comment]
Update:

```
!pip install bleach_whitelist
```

Fixed the first of the three problems above, but not the others.

**Comment by akaihola** [comment]
I may have a similar problem in akaihola/jupyter_abc#2.
