### ISSUE TITLE
How do we update Azure Notebook packages?

### ISSUE THREAD

**Issue by SeaDude** [microsoft/AzureNotebooks#802]
**Example:**
- `pandas` is being imported as version `0.23.4`
- I need version `0.24.0` to use the `.to_numpy()` function

**Tried:**
- Using `Terminal` from the Azure Notebooks project directory
- Running `pip install pandas==0.24.0`
- It successfully downloads the new packages, BUT...

**Error:**
- Receive a `permission denied` error at the end of the installation (as of course, I don't have permissions on the server hosting my notbook.
```
nbuser@nbserver:~$ pip install pandas==0.24.0
Collecting pandas==0.24.0
  Using cached https://files.pythonhosted.org/packages/cb/59/0c68a171af1eb67690f4ca5daf808c798123c7ec94ec83c78780b4a52a18/pandas-0.24.0-cp35-cp35m-manylinux1_x86_64.whl
Requirement already satisfied: python-dateutil>=2.5.0 in /usr/local/lib/python3.5/dist-packages (from pandas==0.24.0)
Collecting pytz>=2011k (from pandas==0.24.0)
  Using cached https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl
Collecting numpy>=1.12.0 (from pandas==0.24.0)
  Using cached https://files.pythonhosted.org/packages/ff/18/c0b937e2f84095ae230196899e56d1d7d76c8e8424fb235ed7e5bb6d68af/numpy-1.18.2-cp35-cp35m-manylinux1_x86_64.whl
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.5/dist-packages (from python-dateutil>=2.5.0->pandas==0.24.0)
Installing collected packages: pytz, numpy, pandas
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.5/dist-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python3.5/dist-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python3.5/dist-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/pytz-2019.3.dist-info'
You are using pip version 9.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
nbuser@nbserver:~$
```

**Question:**
- How do I install another (or the latest) version of the `pandas` library?

Thank you

**Comment by SeaDude** [comment]
PS: Looks like an overall Anaconda update is required in Azure Notebooks!

Running...

```
import sys
import pandas as pd
import numpy as np
from numpy import genfromtxt
import matplotlib.pyplot as plt
from datetime import date
print('Python version ' + sys.version)
print('pandas version:', pd.__version__)
print('numpy version:', np.__version__)
```
...results in...

```
Python version 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0]
pandas version: 0.23.4
numpy version: 1.16.2
```

**Comment by SeaDude** [comment]
Appears you can update packages from within the Azure Notebook rather than by using the terminal. 
https://docs.microsoft.com/en-us/azure/notebooks/install-packages-jupyter-notebook
