### ISSUE TITLE
Old azure-rbac module. Trying to upgrade killed the azure module

### ISSUE THREAD

**Issue by Zappatta** [microsoft/AzureNotebooks#817]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

I was trying to use azure-graphrbac and azure packages to see if I can get information about the currently signed in user (Using the new JIT Azure functionality)

While trying to figure out how to do so. I've noticed that the azure graphrbac module is outdated (0.30.0, while the newest is 0.60.1). 

So I've tried using requirements.txt and specifying the newest version. Created a requirements.txt file with contents: `azure-graphrbac==0.61.1` 
then also set up the requirements.txt in the environment tab under "Projects settings"

After which, it seems that the azure library for python broke,
At first, the azure module didn't have a `graphrbac` module. So was azure.graphrbac was null.

Then I've tried adding `azure==5.0.0` to the requirements file which completely broke the azure module.

running 
`
import azure
dir(azure)
`
now outputs:
`
['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
`

I've then used the clip to try to debug. Tried manually running `pip install -r requirements.txt`
and got an error:
```
Installing collected packages: azure-graphrbac, chardet, urllib3, requests
  Found existing installation: azure-graphrbac 0.30.0
    Uninstalling azure-graphrbac-0.30.0:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.5/shutil.py", line 538, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/azure/graphrbac/__init__.py' -> '/tmp/pip-wsj305zq-uninstall/usr/local/lib/python3.5/dist-packages/azure/graphrbac/__init__.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/local/lib/python3.5/dist-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib/python3.5/shutil.py", line 553, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/azure/graphrbac/__init__.py'
You are using pip version 9.0.1, however version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Stopping and restarting the server did not help

Creating an entirely new project did not help

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

The notebook is private. But I can share link with azure support if needed.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

05.10.2020 starting at around 13:00 GMT (very roughly)

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [X] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)

```
[I 12:39:29.582 NotebookApp] Using MathJax: /OpenSource/mathjax_2-7-5/MathJax.js
[I 12:39:29.604 NotebookApp] Writing notebook server cookie secret to /home/nbuser/.local/share/jupyter/runtime/notebook_cookie_secret
[W 12:39:30.764 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 12:39:30.765 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 12:39:31.202 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.0
[I 12:39:31.309 NotebookApp] JupyterLab beta preview extension loaded from /usr/local/lib/python2.7/dist-packages/jupyterlab
[I 12:39:31.309 NotebookApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 12:39:31.400 NotebookApp] Serving notebooks from local directory: /home/nbuser/library
[I 12:39:31.400 NotebookApp] 0 active kernels
[I 12:39:31.400 NotebookApp] The Jupyter Notebook is running at:
[I 12:39:31.401 NotebookApp] http://nbserver:25198/nb/
[I 12:39:31.401 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[E 13:50:46.709 NotebookApp] Could not open static file ''
[W 13:50:46.711 NotebookApp] 404 GET / (10.36.12.1) 104.77ms referer=None
[I 13:50:50.875 NotebookApp] Kernel started: d4bc4c4f-eeaa-4733-b51d-ab0c8ace3ba0
[I 13:50:56.576 NotebookApp] Adapting to protocol v5.1 for kernel d4bc4c4f-eeaa-4733-b51d-ab0c8ace3ba0
TermSocket.open: 1
[I 13:52:31.146 NotebookApp] New terminal with specified name: 1
TermSocket.open: Opened 1
Websocket closed
[I 14:00:54.353 NotebookApp] Starting buffering for d4bc4c4f-eeaa-4733-b51d-ab0c8ace3ba0:86579acad90b44ed92206ef1e99f51ed
[I 14:01:00.939 NotebookApp] Adapting to protocol v5.1 for kernel d4bc4c4f-eeaa-4733-b51d-ab0c8ace3ba0
[I 14:01:00.941 NotebookApp] Restoring connection for d4bc4c4f-eeaa-4733-b51d-ab0c8ace3ba0:86579acad90b44ed92206ef1e99f51ed
[I 14:03:13.858 NotebookApp] Starting buffering for d4bc4c4f-eeaa-4733-b51d-ab0c8ace3ba0:86579acad90b44ed92206ef1e99f51ed
[I 14:16:22.511 NotebookApp] Adapting to protocol v5.1 for kernel d4bc4c4f-eeaa-4733-b51d-ab0c8ace3ba0
[I 14:16:22.512 NotebookApp] Restoring connection for d4bc4c4f-eeaa-4733-b51d-ab0c8ace3ba0:86579acad90b44ed92206ef1e99f51ed
[
  {
    "environmentName": "AzureCloud",
    "id": "** REDACTED **",
    "isDefault": true,
    "name": "Microsoft Azure Sponsorship",
    "state": "Enabled",
    "tenantId": "** REDACTED **",
    "user": {
      "assignedIdentityInfo": "MSI",
      "name": "systemAssignedIdentity",
      "type": "servicePrincipal"
    }
  }
]
[I 14:23:02.743 NotebookApp] Adapting to protocol v5.1 for kernel d4bc4c4f-eeaa-4733-b51d-ab0c8ace3ba0
TermSocket.open: 1
TermSocket.open: Opened 1```

**Comment by Zappatta** [comment]
UPDATE: It appears that I was on Python 3.5 kernel, and not 3.6. I was able to install on 3.6.
