### ISSUE TITLE
New py3.6 notebooks come with a broken Azure CLI

### ISSUE THREAD

**Issue by v-iam** [Microsoft/AzureNotebooks#97]
### Description

The `az` command in a newly created Python 3.6 notebook raises the following exception:

```
Traceback (most recent call last):
  File "/home/nbuser/anaconda3_431/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/nbuser/anaconda3_431/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nbuser/anaconda3_431/lib/python3.6/site-packages/azure/cli/__main__.py", line 9, in <module>
    import azure.cli.main
  File "/home/nbuser/anaconda3_431/lib/python3.6/site-packages/azure/cli/main.py", line 12, in <module>
    from azure.cli.core._util import (show_version_info_exit, handle_exception)
ModuleNotFoundError: No module named 'azure.cli.core._util'
```

Explicitly installing the most recent version of the CLI resolves this, e.g. `!pip install azure-cli==2.0.6`.

Contrariwise, `!pip install azure-cli` reports that `azure-cli` and all dependencies are installed and does nothing.

### Repro Steps

Create a new Python 3.6 notebook and run `!az --help` (or any other `az` command) in it.

### Usage Scenario (e.g. teaching a computing course at university foo)

Attempting to interact with any Azure services using the CLI in a notebook.

### Recommended Metadata
The Jupyter Kernel (Python2, Python3, R, N/A): Python 3.6
Occurrence Time: 1:50 PM 5/17/2017
Web Browser: Vivaldi
LibraryID and Notebook Name (if applicable): https://notebooks.azure.com/run/v-iam/misc?dest=/notebooks/az-test.ipynb
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable:
```
[I 16:11:38.298 NotebookApp] Using MathJax: /content/mathjax/MathJax.js
[I 16:11:38.328 NotebookApp] Writing notebook server cookie secret to /home/nbuser/.local/share/jupyter/runtime/notebook_cookie_secret
[W 16:11:38.391 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 16:11:38.392 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 16:11:38.424 NotebookApp] JupyterLab alpha preview extension loaded from /usr/local/lib/python2.7/dist-packages/jupyterlab
[W 16:11:38.425 NotebookApp] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 1120, in init_server_extensions
        func(self)
      File "/usr/local/lib/python2.7/dist-packages/jupyterlab/extension.py", line 62, in load_jupyter_server_extension
        PREFIX
    TypeError: add_handlers() takes exactly 2 arguments (5 given)
[I 16:11:38.478 NotebookApp] "Notebook Storage implemented by ipnb.azure"
[I 16:11:38.478 NotebookApp] 0 active kernels 
[I 16:11:38.478 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:19031/n/NLRcOVLBurw/
[I 16:11:38.478 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[E 20:50:08.489 NotebookApp] Could not open static file ''
[W 20:50:08.490 NotebookApp] 404 GET / (172.17.0.1) 23.08ms referer=None
[I 20:50:10.210 NotebookApp] Writing notebook-signing key to /home/nbuser/.local/share/jupyter/notebook_secret
[W 20:50:10.210 NotebookApp] Notebook az-test.ipynb is not trusted
[I 20:50:10.405 NotebookApp] Kernel started: 3ae84344-23b7-4ccf-9564-64961bd33837
[I 20:50:11.506 NotebookApp] Adapting to protocol v5.1 for kernel 3ae84344-23b7-4ccf-9564-64961bd33837
[I 20:52:10.824 NotebookApp] Saving file at /az-test.ipynb
[I 20:52:11.048 NotebookApp] create_checkpoint 'checkpoint' for 'az-test.ipynb' 
[I 20:54:10.743 NotebookApp] Saving file at /az-test.ipynb
[I 20:55:43.554 NotebookApp] Saving file at /az-test.ipynb
[I 20:55:43.336 NotebookApp] create_checkpoint 'checkpoint' for '/az-test.ipynb' 
[W 20:56:59.815 NotebookApp] 404 GET / (172.17.0.1) 1.55ms referer=None
[I 20:57:01.903 NotebookApp] Adapting to protocol v5.1 for kernel 3ae84344-23b7-4ccf-9564-64961bd33837
```

**Comment by brettcannon** [comment]
It's actually because of an incompatibility issue between conda and pip that's causing this. The team is aware of the issue and we hope we have a fix that will go out in a future update.

**Comment by crwilcox** [comment]
Closing this as it should now be fixed. Please reopen this issue if this is in error.
